### ISSUE TITLE
[DOCS ISSUE] Page: Setting up

### ISSUE THREAD

**Issue by yeltsinxyz** [apostrophecms/a3-docs#117]
On the paragraph "Install the CLI tool:" the command is:

```
npm install @apostrophecms/cli
# Or `yarn install`, if you prefer. We'll stick to npm commands.
```

But since the CLI is "global", maybe is better to do -g instead? Because when I try to use `apos` it give me an error.

```
npm install -g @apostrophecms/cli
# Or `yarn install`, if you prefer. We'll stick to npm commands.
```

**Comment by abea** [comment]
The npm part has been fixed, but I've created a PR to address the yarn part as well.
