### ISSUE TITLE
[DOCS ISSUE] Page: Module configuration options

### ISSUE THREAD

**Issue by Miselrkba** [apostrophecms/a3-docs#139]
Outdated link in https://v3.docs.apostrophecms.org/reference/module-api/module-options.html#icon in the list of globally available UI icons points to a 404. 
Correct link should be -https://github.com/apostrophecms/apostrophe/blob/main/modules/@apostrophecms/asset/lib/globalIcons.js

**Comment by abea** [comment]
Thanks!
