### ISSUE TITLE
Missing Page Cookbook on Documentation Website

### ISSUE THREAD

**Issue by chris2fr** [apostrophecms/a3-docs#150]
On page

https://v3.docs.apostrophecms.org/guide/hosting.html#best-practices

there is a link to this non-existant page:

https://v3.docs.apostrophecms.org/docs/cookbook/#hosting

Not sure why Cookbook isn't there on the website. It is here

https://github.com/apostrophecms/a3-docs/blob/main/docs/cookbook/README.md#hosting

https://github.com/apostrophecms/a3-docs/blob/main/docs/guide/hosting.md

**Comment by BoDonkey** [comment]
Currently working. Thanks!
