### ISSUE TITLE
[DOCS ISSUE] Page: Connecting content with relationships

### ISSUE THREAD

**Issue by bmpj1** [apostrophecms/a3-docs#197]
It's possible to add an example for pieces-widgets relationships?

**Comment by boutell** [comment]
Hi Brian, we should but it works no differently from piece-to-piece relationship. Put it in the `fields` section... shows up in the editor.

**Comment by boutell** [comment]
I should provide more context. I think you're asking how to add a relationship to a widget, referencing a piece type. Let me know if that's not what you're asking.

**Comment by bmpj1** [comment]
Hi Tom, the thing is that i have been investigating how to work with the V3 and i have created a piece following [this point](https://v3.docs.apostrophecms.org/guide/pieces.html#creating-a-piece-type) for creating a first test structure:
// modules/product/index.js
module.exports = {
  extend: '@apostrophecms/piece-type',
  options: {
    // module options
  },
  fields: {
    add: {
       // other fields then:
      _images: {
        label: 'Images',
        type: 'relationship',
        // Use `@apostrophecms/file` for non-image files
        withType: '@apostrophecms/image',
        help: 'Pick the images to show in the carousel'
      }
    }
  }
};

After that, i was looking to create a carousel widget for selecting pieces (this works) and display the pieces with custom styles, due to that i have changed the widget area from the piece to a relationship [following this guide](https://v3.docs.apostrophecms.org/reference/field-types/relationship.html#relationship) and i could retrieve data from this relationship with nunjucks but can't get how to print the images on the widget.

At the end, i managed to do a carousel for images with links to internal/external pages, but not for the custom pieces.
