### ISSUE TITLE
No favicon set

### ISSUE THREAD

**Issue by BoDonkey** [apostrophecms/a3-docs#214]
## The problem to solve

Is your feature request related to a problem you are experiencing that is *not* a bug? Please describe.

> A clear and concise description of what the problem is. Ex: "When I do [some task], I find it frustrating when [something happens]." If this is a bug report (things are actually breaking), open a bug report instead.

Currently, the a3 doc pages do not have a favicon set.

## Proposed solution

Describe the solution you'd like

> A clear and concise description of what you want to happen.

An ApostropheCMS or other appropriate favicon should be added to the documentation pages. It is unclear if this should be the same as the main pages or not.

## Alternatives

Describe alternatives you've considered

> A clear and concise description of any alternative solutions or features you've considered. For example, should this be done on the project level instead?

## Additional context

> Mention any other context or attach screenshots regarding the feature request.
> Check the existing issue labels and add any you think are relevant, e.g.,
> `UI`, `UX`, `accessibility`, `security`.

**Comment by boutell** [comment]
Please also add this ticket to our internal linear board for apostrophe, and assign it to Alex under "triage."
