### ISSUE TITLE
[DOCS ISSUE] Page: Building site navigation

### ISSUE THREAD

**Issue by LeviticusMaximus** [apostrophecms/a3-docs#229]
The custom URL field is incorrectly referenced in the _views/layout.html_ example. For this to work: 

```
{% elif item.type === 'custom' %}
   {% set path = item.url %}
{% endif %}
```
Needs to be changed to:

```
{% elif item.type === 'custom' %}
   {% set path = item.customUrl %}
{% endif %}
```

...might save someone scratching their heads 👋

**Comment by boutell** [comment]
Sounds right... assigning to Bob to have a look... thanks for the note!

**Comment by BoDonkey** [comment]
Fixed with PR 230 - Thanks!
