### ISSUE TITLE
Grouping New Pieces in the Admin Bar

### ISSUE THREAD

**Issue by LeviticusMaximus** [apostrophecms/a3-docs#240]
## How can I Group New Pieces in the Admin Bar?

When I create new piece types, I get a link to manage that piece type in the admin bar.
I would like to be able to group these new pieces - and potentially existing default pieces - into dropdowns in the admin bar, for example:

**Page Content** 

> - Reviews 
> - Testimonials
> - Offices

**Imagery** 

> - Images 
> - Image Tags

Etc...

Is this something that is already possible?
I have not found it covered in the docs.

Thanks

**Comment by boutell** [comment]
cc @BoDonkey

**Comment by BoDonkey** [comment]
Hi @LeviticusMaximus,
Thanks for the question. This is definitely possible. One of the options for the `admin-bar` module is `groups`. This option lets you add new menu items with current pieces - both default and custom - grouped inside. Here is the [link](https://v3.docs.apostrophecms.org/reference/modules/admin-bar.html#configuration-options).
