### ISSUE TITLE
[DOCS ISSUE] Page: Accessing the database directly

### ISSUE THREAD

**Issue by hankhero** [apostrophecms/a3-docs#308]
Syntax error in code, methods self should have a return statement.

     methods (self) {
        return {
    async addNewDog(req, initialInfo) {
  
Also, it is unclear how to actually do this step: "For example, if we had a dog adoption website that used an external API, we may want to update dog pieces periodically with adoption status. This may be using a command line task that is run regularly by a cron job."

So, how would you do that kind of command-line task? How do you get access to the module and invoke addNewDog?

Best regards

**Comment by boutell** [comment]
Good catch re: the syntax error. Feel free to send a PR if you wish.

There is coverage of how to write a task here:

https://v3.docs.apostrophecms.org/reference/module-api/module-overview.html#tasks-self

It is a bit buried here, we should add an "advanced topics" page about tasks. Good example there though.
