### ISSUE TITLE
Example localization configuration produces error

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/a3-docs#310]
https://github.com/apostrophecms/a3-docs/blob/2c7eba8ba36950be6daf2d3b813ef7980eb88250/docs/guide/localization/README.md?plain=1#L38-L58

Gives me the error 
```
Error: The locale "es" cannot be distinguished from earlier locales.
Make sure it is uniquely distinguished by its hostname option,
prefix option or a combination of the two.
One locale per site may be a default with neither hostname nor prefix,
and one locale per hostname may be a default for that hostname without a prefix.
```

I reset my local db, thinking it could have been previous config get tangled up but it also happens on a fresh db. Is this config wrong?

**Comment by boutell** [comment]
Hmm, the example is wrong. Every locale must be fully distinguished by prefix, custom hostname, or some combination of the two — there can be a locale with no prefix, but not more than one on the same hostname. So the example must reflect that requirement.

**Comment by boutell** [comment]
Bob can you take this one on?
