### ISSUE TITLE
TYPO - PR - Question 

### ISSUE THREAD

**Issue by stevenrhett** [apostrophecms/a3-docs#315]
Typo  on line 10 of 

apos-app/modules/@apostrophecms/home-page/views/page.html

"Even with fancy spell checking IDE plugins, mistakes happen. If you've found spelling mistakes"

Should I submit this as a bug?

![typo-apos-app-html](https://user-images.githubusercontent.com/79732886/225981466-fe8e6f3e-0aca-483a-9da6-d4d7b6ac3aa0.png)

**Comment by BoDonkey** [comment]
Well, would you look at that! You can turn your label into a "bug" label, or submit a PR with a fix. Either way, we are much obliged.

**Comment by stevenrhett** [comment]
Thank you for getting back to me. I'll use the new boilerplate and submit a pr in the morning.

**Comment by stevenrhett** [comment]
When checking the  @latest version the correction was completed. 
<img width="1265" alt="2023-03-29 @ 4 07 40 PM" src="https://user-images.githubusercontent.com/79732886/228655686-6e8dc18c-4ead-47cc-b4d9-7fa56d003d56.png">
